import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "infinitive.cc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-3xl">
          {children}
        </div>
      </body>
    </html>
  );
}
